language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - make -C travis test

cache:
  directories:
    - travis/dependencies

env:
  - USE_FRAMEBUFFER=false _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=10000"
